List<Map> profileNames = [
  {'name': 'Software Engineer', 'checked': false},
  {'name': 'Web Developer', 'checked': false},
  {'name': 'Data Scientist', 'checked': false},
  {'name': 'Network Engineer', 'checked': false},
  {'name': 'Systems Analyst', 'checked': false},
  {'name': 'Database Administrator', 'checked': false},
  {'name': 'IT Support Specialist', 'checked': false},
  {'name': 'Cybersecurity Analyst', 'checked': false},
  {'name': 'UI/UX Designer', 'checked': false},
  {'name': 'Cloud Engineer', 'checked': false},
  {'name': 'DevOps Engineer', 'checked': false},
  {'name': 'QA Engineer', 'checked': false},
  {'name': 'Business Analyst', 'checked': false},
  {'name': 'Mobile App Developer', 'checked': false},
  {'name': 'AI/Machine Learning Engineer', 'checked': false},
  {'name': 'IT Project Manager', 'checked': false},
  {'name': 'Technical Writer', 'checked': false},
  {'name': 'IT Consultant', 'checked': false},
  {'name': 'Systems Administrator', 'checked': false},
  {'name': 'Full Stack Developer', 'checked': false},
  {'name': 'Frontend Developer', 'checked': false},
  {'name': 'Backend Developer', 'checked': false},
  {'name': 'Network Administrator', 'checked': false},
  {'name': 'Software Architect', 'checked': false},
  {'name': 'IT Trainer', 'checked': false},
  {'name': 'Data Analyst', 'checked': false},
  {'name': 'Embedded Systems Engineer', 'checked': false},
  {'name': 'Computer Hardware Engineer', 'checked': false},
  {'name': 'Game Developer', 'checked': false},
  {'name': 'UI/UX Developer', 'checked': false},
  {'name': 'IT Auditor', 'checked': false},
  {'name': 'Computer Vision Engineer', 'checked': false},
  {'name': 'IT Sales Professional', 'checked': false},
  {'name': 'IT Recruiter', 'checked': false},
  {'name': 'Technical Support Engineer', 'checked': false},
  {'name': 'System Security Analyst', 'checked': false},
  {'name': 'Software Quality Assurance Engineer', 'checked': false},
  {'name': 'Data Engineer', 'checked': false},
  {'name': 'Desktop Support Engineer', 'checked': false},
  {'name': 'Network Security Engineer', 'checked': false},
  {'name': 'Machine Learning Engineer', 'checked': false},
  {'name': 'Site Reliability Engineer', 'checked': false},
  {'name': 'IT Operations Manager', 'checked': false},
  {'name': 'System Analyst', 'checked': false},
  {'name': 'Software Development Engineer', 'checked': false},
  {'name': 'Systems Engineer', 'checked': false},
  {'name': 'IT Director', 'checked': false},
  {'name': 'Information Security Analyst', 'checked': false},
  {'name': 'Technology Consultant', 'checked': false},
  {'name': 'Data Scientist', 'checked': false},
  {'name': 'IT Technician', 'checked': false},
  {'name': 'Technical Consultant', 'checked': false},
  {'name': 'Cloud Architect', 'checked': false},
  {'name': 'DevOps Engineer', 'checked': false},
  {'name': 'IT Business Analyst', 'checked': false},
  {'name': 'Software Tester', 'checked': false},
  {'name': 'UI/UX Designer', 'checked': false},
  {'name': 'Network Architect', 'checked': false},
  {'name': 'Application Developer', 'checked': false},
  {'name': 'Systems Architect', 'checked': false},
  {'name': 'Data Architect', 'checked': false},
  {'name': 'Web Designer', 'checked': false},
  {'name': 'Database Developer', 'checked': false},
  {'name': 'Mobile Developer', 'checked': false},
  {'name': 'Security Analyst', 'checked': false},
  {'name': 'Technical Support Specialist', 'checked': false},
  {'name': 'Software Developer', 'checked': false},
  {'name': 'Product Manager', 'checked': false},
  {'name': 'IT Manager', 'checked': false},
  {'name': 'Computer Programmer', 'checked': false},
  {'name': 'Artificial Intelligence Engineer', 'checked': false},
  {'name': 'Cloud Solutions Architect', 'checked': false},
  {'name': 'UI Developer', 'checked': false},
  {'name': 'Integration Engineer', 'checked': false},
  {'name': 'Data Engineer', 'checked': false},
  {'name': 'Business Intelligence Analyst', 'checked': false},
  {'name': 'Cybersecurity Engineer', 'checked': false},
  {'name': 'Software Engineer', 'checked': false},
  {'name': 'UX Designer', 'checked': false},
  {'name': 'Technical Writer', 'checked': false},
  {'name': 'QA Analyst', 'checked': false},
  {'name': 'Network Engineer', 'checked': false},
  {'name': 'IT Analyst', 'checked': false},
  {'name': 'Software Architect', 'checked': false},
  {'name': 'Front-End Developer', 'checked': false},
  {'name': 'Back-End Developer', 'checked': false},
  {'name': 'Java Developer', 'checked': false},
  {'name': 'Python Developer', 'checked': false},
  {'name': 'Ruby Developer', 'checked': false},
  {'name': 'C++ Developer', 'checked': false},
  {'name': 'C# Developer', 'checked': false},
  {'name': 'PHP Developer', 'checked': false},
  {'name': 'SQL Developer', 'checked': false},
  {'name': 'Android Developer', 'checked': false},
  {'name': 'iOS Developer', 'checked': false},
  {'name': 'Windows Developer', 'checked': false},
  {'name': 'Linux Developer', 'checked': false},
  {'name': 'Unix Developer', 'checked': false},
  {'name': 'Embedded Systems Developer', 'checked': false},
  {'name': 'Machine Learning Developer', 'checked': false},
  {'name': 'Blockchain Developer', 'checked': false},
  {'name': 'AR/VR Developer', 'checked': false},
  {'name': 'Gaming Developer', 'checked': false},
  {'name': 'Enterprise Application Developer', 'checked': false},
  {'name': 'Mobile App Developer', 'checked': false},
  {'name': 'Web App Developer', 'checked': false},
  {'name': 'Cloud Developer', 'checked': false},
  {'name': 'Full Stack Developer', 'checked': false},
  {'name': 'Front-End Engineer', 'checked': false},
  {'name': 'Back-End Engineer', 'checked': false}
];
